---
title: "Histórico das aulas do curso"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE}
source("setup_knitr.R")
```

Abaixo o histórico de atividades realizadas em classe e atividades extra
classe aplicadas.

- **01/08**: Não houve aula devido ao
  [Software Carpentry - UFPR](http://abelsiqueira.github.io/2016-08-01-ufpr)
- **03/08**: Não houve aula devido ao
  [Software Carpentry - UFPR](http://abelsiqueira.github.io/2016-08-01-ufpr)
- **08/08**: Apresentação da disciplina. Ver os
  [slides](01_introducao_e_amostragem/01_Introducao_a_Estatistica_e_amostragem.pdf).
- **10/08**: Introdução a Estatística e tipos de amostragem.
  [Slides](01_introducao_e_amostragem/01_Introducao_a_Estatistica_e_amostragem.pdf).
- **15/08**: Não haverá aula
- **17/08**: Não haverá aula
- **22/08**: Tipos de amostragem probabilística e exercícios.
  [Slides](01_introducao_e_amostragem/01_Introducao_a_Estatistica_e_amostragem.pdf).
- **24/08**: Análise exploratória de dados: classificação de variáveis.
  Tabelas e gráficos para variáveis qualitativas.
  [Material](02_Analise_Exploratoria_de_Dados.html).
- **29/08**: Tabelas e gráficos para variáveis quantitativas discretas.
  [Material](02_Analise_Exploratoria_de_Dados.html).
- **31/08**: Tabelas e gráficos para variáveis quantitativas contínuas.
  [Material](02_Analise_Exploratoria_de_Dados.html).
- **05/09**: Medidas de tendência central: moda, mediana e
  média. [Slides](03_Medidas_resumo/03_Medidas_resumo.pdf)

## Exercícios

- [Lista 1][]: Amostragem e análise exploratória de dados. [Gabarito 1][].
- [Lista 2][]: Medidas resumo.

## Notas

As notas estão disponíveis [nesta página](notas.html).


[Lista 1]: exercicios/01_Amostragem_e_Exploratoria.pdf
[Gabarito 1]: exercicios/01_Amostragem_e_Exploratoria_GABARITO.pdf
[Lista 2]: exercicios/03_Medidas_resumo.pdf
[Gabarito 2]: exercicios/03_Medidas_resumo_GABARITO.pdf
